const DAILY_INSIGHTS = [
  { text: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
  { text: "Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.", author: "Roberto Shinyashiki" },
  { text: "Não tenha medo de desistir do bom para perseguir o ótimo.", author: "John D. Rockefeller" },
  { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
  { text: "Conheça todas as teorias, domine todas as técnicas, mas ao tocar uma alma humana, seja apenas outra alma humana.", author: "Carl Jung" },
  { text: "Onde não há visão, o povo perece.", author: "Provérbios 29:18" },
  { text: "Porque eu sei os planos que tenho para vocês, planos de prosperidade e não de calamidade, para dar-lhes um futuro e uma esperança.", author: "Jeremias 29:11" },
  { text: "O único lugar onde o sucesso vem antes do trabalho é no dicionário.", author: "Vidal Sassoon" },
  { text: "Sua empresa é um reflexo de você. Se você é preguiçoso, sua empresa será preguiçosa.", author: "Mark Cuban" },
  { text: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.", author: "Charles Darwin" },
  { text: "Peçam, e será dado; busquem, e encontrarão; batam, e a porta será aberta.", author: "Mateus 7:7" },
  { text: "Marketing não é mais sobre as coisas que você faz, mas sobre as histórias que você conta.", author: "Seth Godin" },
  { text: "Inovação distingue um líder de um seguidor.", author: "Steve Jobs" },
  { text: "Você não precisa ser grande para começar, mas precisa começar para ser grande.", author: "Zig Ziglar" },
  { text: "O segredo de progredir é começar.", author: "Mark Twain" },
  { text: "Tudo posso naquele que me fortalece.", author: "Filipenses 4:13" },
  { text: "Clientes insatisfeitos são sua maior fonte de aprendizado.", author: "Bill Gates" },
  { text: "O preço da excelência é a prática constante.", author: "Aristóteles" },
  { text: "Se você quer ir rápido, vá sozinho. Se você quer ir longe, vá acompanhado.", author: "Provérbio Africano" },
  { text: "A melhor maneira de prever o futuro é criá-lo.", author: "Peter Drucker" },
  { text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento.", author: "Provérbios 3:5" },
  { text: "Pessoas não compram o que você faz, elas compram o porquê você faz.", author: "Simon Sinek" },
  { text: "O sucesso geralmente vem para quem está ocupado demais para procurá-lo.", author: "Henry David Thoreau" },
  { text: "A única coisa que fica entre você e o seu sonho é a vontade de tentar e a crença de que é possível.", author: "Joel Brown" },
  { text: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente.", author: "Romanos 12:2" },
  { text: "O maior risco é não correr nenhum risco. Num mundo que muda rápido, a única estratégia que garante fracasso é não arriscar.", author: "Mark Zuckerberg" },
  { text: "Cultura come estratégia no café da manhã.", author: "Peter Drucker" },
  { text: "Antes de ser um líder, o sucesso é sobre crescer a si mesmo. Quando você se torna um líder, sucesso é sobre crescer os outros.", author: "Jack Welch" },
  { text: "A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", author: "Hebreus 11:1" },
  { text: "Seu trabalho vai preencher grande parte da sua vida. A única maneira de estar satisfeito é fazer o que você acredita ser um grande trabalho.", author: "Steve Jobs" },
  { text: "Quem planta com lágrimas, colherá com alegria.", author: "Salmos 126:5" },
  { text: "Foco não é dizer sim para a coisa em que você vai se focar. É dizer não para as outras cem boas ideias.", author: "Steve Jobs" },
  { text: "A velocidade do líder determina a velocidade do bando.", author: "Ralph Waldo Emerson" },
  { text: "Empreender é resolver problemas de forma lucrativa.", author: "Flávio Augusto" },
  { text: "Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dará muito fruto.", author: "João 15:5" },
  { text: "O marketing autêntico não é a arte de vender o que você faz, mas de saber o que fazer.", author: "Philip Kotler" },
  { text: "O fracasso é simplesmente a oportunidade de começar de novo, desta vez de forma mais inteligente.", author: "Henry Ford" },
  { text: "Se você não pode medir, você não pode gerenciar.", author: "Peter Drucker" },
  { text: "Esforçai-vos, e tende bom ânimo; não temais, porque o Senhor vosso Deus é convosco.", author: "Josué 1:9" },
  { text: "Não encontre clientes para seus produtos, encontre produtos para seus clientes.", author: "Seth Godin" },
  { text: "Grandes realizações não são feitas por impulso, mas por uma soma de pequenas realizações.", author: "Vincent van Gogh" },
  { text: "A diferença entre pessoas de sucesso e pessoas muito bem-sucedidas é que pessoas muito bem-sucedidas dizem não para quase tudo.", author: "Warren Buffett" },
  { text: "Porque onde estiver o vosso tesouro, aí estará também o vosso coração.", author: "Mateus 6:21" },
  { text: "Faça o seu melhor. O que você plantar agora, colherá mais tarde.", author: "Og Mandino" },
  { text: "Se eu tivesse perguntado às pessoas o que elas queriam, teriam dito cavalos mais rápidos.", author: "Henry Ford" },
  { text: "Negócios têm apenas duas funções: marketing e inovação.", author: "Peter Drucker" },
  { text: "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.", author: "Isaías 40:31" },
  { text: "Disciplina é a ponte entre metas e realizações.", author: "Jim Rohn" },
  { text: "O empreendedor sempre procura a mudança, reage a ela e a explora como uma oportunidade.", author: "Peter Drucker" },
  { text: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.", author: "Salmos 119:105" },
  { text: "Construa algo que 100 pessoas amem, não algo que 1 milhão de pessoas meio que gostam.", author: "Paul Graham" },
  { text: "Os vencedores encontram caminhos. Os perdedores, desculpas.", author: "Napoleon Hill" },
  { text: "A coragem não é a ausência de medo, mas a capacidade de agir apesar dele.", author: "Nelson Mandela" },
  { text: "Pois o Senhor dá sabedoria; de sua boca procedem conhecimento e discernimento.", author: "Provérbios 2:6" },
  { text: "Quem quer fazer encontra um meio; quem não quer encontra uma desculpa.", author: "Roberto Shinyashiki" },
  { text: "O conteúdo constrói relacionamentos. Relacionamentos são baseados em confiança. Confiança gera receita.", author: "Andrew Davis" },
  { text: "A simplicidade é a sofisticação suprema.", author: "Leonardo da Vinci" },
  { text: "Comece de onde você está. Use o que você tem. Faça o que puder.", author: "Arthur Ashe" },
  { text: "Ensina-nos a contar os nossos dias, para que alcancemos coração sábio.", author: "Salmos 90:12" },
  { text: "Não tenha medo de abandonar o bom para perseguir o ótimo.", author: "John D. Rockefeller" },
  { text: "Seja a mudança que você deseja ver no mundo.", author: "Mahatma Gandhi" },
  { text: "O homem sábio poupa para o futuro, mas o tolo gasta tudo que ganha.", author: "Provérbios 21:20" },
  { text: "O cliente não é uma interrupção do nosso trabalho. Ele é o propósito dele.", author: "Mahatma Gandhi" },
  { text: "O que nos dá medo nos dá asas.", author: "Augusto Cury" },
  { text: "Bem-aventurado o homem que suporta a tentação; porque, depois de aprovado, receberá a coroa da vida.", author: "Tiago 1:12" },
  { text: "Lucro é a consequência de fazer as coisas certas para os clientes.", author: "Jeff Bezos" },
  { text: "As pessoas não sabem o que querem até você mostrar a elas.", author: "Steve Jobs" },
  { text: "Trabalhe como se tudo dependesse de você, ore como se tudo dependesse de Deus.", author: "Santo Agostinho" },
  { text: "O verdadeiro teste de liderança é quão bem você funciona em uma crise.", author: "Brian Tracy" },
  { text: "Mas buscai primeiro o seu reino e a sua justiça, e todas essas coisas vos serão acrescentadas.", author: "Mateus 6:33" },
  { text: "Se o plano não funcionar, mude o plano, mas nunca mude a meta.", author: "Autor Desconhecido" },
  { text: "Marca não é o que você diz que é. Marca é o que os outros dizem que é.", author: "Jeff Bezos" },
  { text: "A excelência não é um ato, mas um hábito.", author: "Aristóteles" },
  { text: "Posso não ter chegado onde pretendia ir, mas acho que acabei onde pretendia estar.", author: "Douglas Adams" },
  { text: "O Senhor é o meu pastor; nada me faltará.", author: "Salmos 23:1" },
  { text: "Toda grande empresa nasceu como uma pequena empresa com uma grande visão.", author: "Brian Tracy" },
  { text: "Não fique esperando. O momento nunca será perfeito.", author: "Napoleon Hill" },
  { text: "O homem que move montanhas começa carregando pequenas pedras.", author: "Confúcio" },
  { text: "Pois nada é impossível para Deus.", author: "Lucas 1:37" },
  { text: "Não basta conquistar clientes. É preciso mantê-los.", author: "Philip Kotler" },
  { text: "O impossível existe até que alguém duvide e resolva provar o contrário.", author: "Albert Einstein" },
  { text: "Quando tudo parecer ir contra você, lembre-se que o avião decola contra o vento.", author: "Henry Ford" },
  { text: "Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.", author: "Eclesiastes 3:1" },
  { text: "Uma empresa que não inova envelhece e morre.", author: "Luiza Trajano" },
  { text: "Cuide dos seus funcionários e eles cuidarão dos seus clientes.", author: "Richard Branson" },
  { text: "Não julgue cada dia pela colheita que você obtém, mas pelas sementes que você planta.", author: "Robert Louis Stevenson" },
  { text: "Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", author: "2 Timóteo 1:7" },
  { text: "A propaganda é a alma do negócio.", author: "Provérbio Popular" },
  { text: "Cada dia é uma nova chance de mudar sua vida.", author: "Autor Desconhecido" },
  { text: "A persistência realiza o impossível.", author: "Provérbio Chinês" },
  { text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor.", author: "Jeremias 29:11" },
  { text: "Se você realmente quer fazer algo, encontrará um caminho. Se não quiser, encontrará uma desculpa.", author: "Jim Rohn" },
  { text: "Estratégia sem tática é o caminho mais lento para a vitória. Tática sem estratégia é o ruído antes da derrota.", author: "Sun Tzu" },
  { text: "Gentileza gera gentileza.", author: "Provérbio Popular" },
  { text: "O Senhor é a minha luz e a minha salvação; de quem terei medo?", author: "Salmos 27:1" },
  { text: "Sucesso não é sobre o destino, é sobre a jornada.", author: "Zig Ziglar" },
  { text: "Quanto mais suor no treino, menos sangue na batalha.", author: "Provérbio Militar" },
  { text: "A gratidão transforma o que temos em suficiente.", author: "Melody Beattie" },
  { text: "O que é impossível para os homens é possível para Deus.", author: "Lucas 18:27" },
  { text: "Não espere condições perfeitas. Comece agora com o que tem.", author: "Autor Desconhecido" },
  { text: "Um líder é aquele que conhece o caminho, percorre o caminho e mostra o caminho.", author: "John Maxwell" },
  { text: "A sorte favorece a mente preparada.", author: "Louis Pasteur" },
  { text: "Eu vim para que tenham vida e a tenham em abundância.", author: "João 10:10" },
  { text: "A humildade precede a honra.", author: "Provérbios 15:33" },
  { text: "Não tenha medo de dar um grande passo. Não se pode cruzar um abismo com dois pequenos saltos.", author: "David Lloyd George" },
  { text: "A chave da mudança está na energia focada, não na força.", author: "Aikido" },
  { text: "Delight the customer. Make it your strategy, not just your slogan.", author: "Autor Desconhecido" },
  { text: "Clame a mim e eu responderei, e direi coisas grandes e ocultas que você não conhece.", author: "Jeremias 33:3" },
  { text: "O verdadeiro empreendedor é um fazedor, não um sonhador.", author: "Nolan Bushnell" },
  { text: "Quem semeia com fartura também colherá fartamente.", author: "2 Coríntios 9:6" },
  { text: "Os detalhes não são detalhes. Eles fazem o design.", author: "Charles Eames" },
  { text: "A ação é a chave fundamental de todo sucesso.", author: "Pablo Picasso" },
  { text: "Aprenda como se fosse viver para sempre. Viva como se fosse morrer amanhã.", author: "Mahatma Gandhi" },
  { text: "Revesti-vos de toda armadura de Deus para que possais estar firmes contra as astutas ciladas do diabo.", author: "Efésios 6:11" },
  { text: "Não é preciso ter olhos abertos para ver o sol, nem é preciso ter coração aberto para sentir a verdade.", author: "Autor Desconhecido" },
  { text: "O homem diligente obterá riquezas preciosas.", author: "Provérbios 12:27" },
  { text: "Crie valor antes de capturar valor.", author: "Paul Graham" },
  { text: "Coragem é resistência ao medo, domínio do medo — e não ausência do medo.", author: "Mark Twain" },
  { text: "Sabedoria é a coisa principal; adquire, pois, a sabedoria; e com tudo o que possuis adquire o entendimento.", author: "Provérbios 4:7" },
  { text: "Fracassar é parte do jogo. A questão é saber se levantar.", author: "Autor Desconhecido" },
  { text: "Nenhum de nós é tão bom quanto todos nós juntos.", author: "Ray Kroc" },
  { text: "O otimista vê oportunidade em toda dificuldade.", author: "Winston Churchill" },
  { text: "Eu plantei, Apolo regou; mas Deus deu o crescimento.", author: "1 Coríntios 3:6" },
  { text: "Quem não arrisca, não petisca.", author: "Provérbio Popular" },
  { text: "Invista em você mesmo. Seu conhecimento é seu maior ativo.", author: "Warren Buffett" },
  { text: "Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.", author: "Salmos 37:5" },
  { text: "O mundo pertence aos otimistas; os pessimistas são meros espectadores.", author: "Dwight D. Eisenhower" },
  { text: "A maior glória não é nunca cair, mas levantar-se sempre.", author: "Confúcio" },
  { text: "Sejam fortes e corajosos. Não tenham medo nem fiquem apavorados, pois o Senhor vai com vocês.", author: "Deuteronômio 31:6" },
  { text: "O bom é inimigo do ótimo.", author: "Voltaire" },
  { text: "Não espere a oportunidade bater na porta. Construa uma porta.", author: "Milton Berle" },
  { text: "Aquele que começou boa obra em vocês, vai completá-la até o dia de Cristo Jesus.", author: "Filipenses 1:6" },
  { text: "A criatividade é a inteligência se divertindo.", author: "Albert Einstein" },
  { text: "O maior patrimônio de uma empresa é o seu time.", author: "Jorge Paulo Lemann" },
  { text: "A fé sem obras é morta.", author: "Tiago 2:26" },
  { text: "Só existe uma coisa pior do que formar colaboradores e eles partirem: é não os formar e eles ficarem.", author: "Henry Ford" },
  { text: "O dinheiro é consequência, nunca o objetivo.", author: "Abílio Diniz" },
  { text: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.", author: "Romanos 8:28" },
];

export const getDailyInsight = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  const index = dayOfYear % DAILY_INSIGHTS.length;
  return DAILY_INSIGHTS[index];
};
